const fs = require('fs');
const path = require('path');
const target = path.join(__dirname, '..', 'src', 'components', 'AIChatInline.tsx');
let c = fs.readFileSync(target, 'utf8');

// 1. Fix header: avatar+name+status on LEFT, "返回工作台" on RIGHT
c = c.replace(
  'className="max-w-[1200px] mx-auto flex items-center justify-between">\n          <button\n            onClick={exitChat}\n            className="flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors"\n          >\n            <ArrowUp className="w-4 h-4" />\n            <span>返回工作台</span>\n          </button>\n          <div className="w-px h-5 bg-border" />\n          <div className="w-8 h-8 rounded-full overflow-hidden border border-border">\n            <img src={agentImage} alt={agentName} className="w-full h-full object-cover" />\n          </div>\n          <div>\n            <div className="text-sm font-medium text-foreground">{agentName}</div>\n            <div className="text-[11px] text-muted-foreground flex items-center gap-1">\n              <span className="w-1.5 h-1.5 rounded-full bg-success inline-block" />\n              在线\n            </div>\n          </div>',
  'className="max-w-[1200px] mx-auto flex items-center justify-between">\n          <div className="flex items-center gap-3">\n            <div className="w-8 h-8 rounded-full overflow-hidden border border-border">\n              <img src={agentImage} alt={agentName} className="w-full h-full object-cover" />\n            </div>\n            <div>\n              <div className="text-sm font-medium text-foreground">{agentName}</div>\n              <div className="text-[11px] text-muted-foreground flex items-center gap-1">\n                <span className="w-1.5 h-1.5 rounded-full bg-success inline-block" />\n                在线\n              </div>\n            </div>\n          </div>\n          <button\n            onClick={exitChat}\n            className="flex items-center gap-1.5 text-sm font-medium text-muted-foreground hover:text-primary transition-colors"\n          >\n            <ArrowUp className="w-4 h-4 -rotate-90" />\n            <span>返回工作台</span>\n          </button>'
);

// 2. Messages area: fix max-w to 1200px
c = c.replace(
  '<div className="flex-1 px-6 py-6">\n        <div className="max-w-[800px] mx-auto space-y-5">',
  '<div className="flex-1 px-6 lg:px-8 py-6">\n        <div className="max-w-[1200px] mx-auto space-y-5">'
);

// 3. Input box: match main workspace size (px-5 py-3.5, gap-4, w-9 h-9, w-5 h-5 sparkles)
c = c.replace(
  '<div className="sticky bottom-0 bg-gradient-to-t from-background via-background to-transparent pt-4 pb-4 px-6">\n        <div className="max-w-[800px] mx-auto">\n          <div className="flex items-center gap-3 bg-card border border-border rounded-2xl px-4 py-2.5 shadow-elevated focus-within:shadow-glow focus-within:border-primary/40 transition-shadow">\n            <Sparkles className="w-4 h-4 text-primary shrink-0" />\n            <input\n              type="text"\n              value={input}\n              onChange={(e) => setInput(e.target.value)}\n              onKeyDown={(e) => e.key === "Enter" && handleSend()}\n              placeholder={`?{agentName}提问...`}\n              className="flex-1 bg-transparent text-sm text-foreground placeholder:text-muted-foreground outline-none"\n            />\n            <button\n              onClick={handleSend}\n              disabled={!input.trim()}\n              className="w-8 h-8 rounded-xl bg-primary text-primary-foreground flex items-center justify-center disabled:opacity-30 hover:bg-primary/90 transition-all shrink-0"\n            >\n              <Send className="w-3.5 h-3.5" />\n            </button>\n          </div>\n          <p className="text-center text-[11px] text-muted-foreground/60 mt-2">\n            AI 助手基于内部数据提供参考，重要决策请以实际数据为准\n          </p>\n        </div>\n      </div>',
  '<div className="sticky bottom-0 bg-gradient-to-t from-background via-background to-transparent pt-4 pb-4 px-6 lg:px-8">\n        <div className="max-w-[1200px] mx-auto">\n          <div className="flex items-center gap-4 bg-card border border-border rounded-2xl px-5 py-3.5 shadow-elevated focus-within:shadow-glow focus-within:border-primary/40 transition-shadow">\n            <Sparkles className="w-5 h-5 text-primary shrink-0" />\n            <input\n              type="text"\n              value={input}\n              onChange={(e) => setInput(e.target.value)}\n              onKeyDown={(e) => e.key === "Enter" && handleSend()}\n              placeholder={`向${agentName}提问...`}\n              className="flex-1 bg-transparent text-sm text-foreground placeholder:text-muted-foreground outline-none"\n            />\n            <button\n              onClick={handleSend}\n              disabled={!input.trim()}\n              className="w-9 h-9 rounded-xl bg-primary text-primary-foreground flex items-center justify-center disabled:opacity-30 hover:bg-primary/90 transition-all shrink-0"\n            >\n              <Send className="w-4 h-4" />\n            </button>\n          </div>\n          <p className="text-center text-[11px] text-muted-foreground/60 mt-3">\n            AI 助手基于内部数据提供参考，重要决策请以实际数据为准\n          </p>\n        </div>\n      </div>'
);

fs.writeFileSync(target, c);
console.log('Done');
